services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:2.8-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - caddy_data:/data
      - slides_volume:/app/public/slides:ro
    networks:
      - proxy_net
    restart: unless-stopped
    labels:
      caddy.email: ${CADDY_EMAIL}

  backend:
    image: ghcr.io/lazuardiyasfin/carbonfreeclass-backend:${IMAGE_TAG:-latest}
    restart: unless-stopped
    networks: 
      - proxy_net
    labels:
      caddy: ${BACKEND_DOMAIN}
      caddy.reverse_proxy: "{{upstreams 6767}}"

  worker:                          
    image: ghcr.io/lazuardiyasfin/carbonfreeclass-worker:${IMAGE_TAG:-latest}
    restart: unless-stopped
    networks:
      - proxy_net
    volumes:
      - slides_volume:/app/public/slides
    labels:
      caddy: ${BACKEND_DOMAIN}
      caddy.0_reverse_proxy: "/upload/* {{upstreams 8080}}"
      caddy.1_handle_path: /slides/*
      caddy.1_handle_path.0_root: "* /app/public/slides"
      caddy.1_handle_path.1_file_server: ""
      caddy.@upload_options.path: /upload/*
      caddy.@upload_options.method: OPTIONS
      caddy.respond: "@upload_options 204"
      caddy.@upload.path: /upload/*
      caddy.header_1: '@upload Access-Control-Allow-Origin "${FRONTEND_DOMAIN}"'
      caddy.header_2: '@upload Access-Control-Allow-Methods "POST, OPTIONS"'
      caddy.header_3: '@upload Access-Control-Allow-Headers "*"'

volumes:
  caddy_data:
  